export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";
export const CLEAR_SELECTED_EMPLOYEE = "CLEAR_SELECTED_EMPLOYEE";