export const MEDICAL_PROFILE = "Medical Profile"
export const APPOINTMENTS = "Appointments"
export const QR_PRESCRIPTION = "QR Prescription"
export const LAB_RESULTS = "Lab Results"
export const ACCOUNT = "ACCOUNT"
export const FAMILY_MEMBERS = "FAMILY_MEMBERS"
export const SICK_LEAVES = "SICK_LEAVES"
//export const REWARDS = "REWARDS"