export const DOCTOR_SLOT = "DOCTOR"
export const PCR_TEST_SLOT = "PCR_TEST"
export const PCR_VACCINATION_SLOT = "PCR_VACCINATION"
export const SELECTED_DOCTOR_OR_HOSPITAL = "SELECTED_DOCTOR_OR_HOSPITAL"